config/routes.rb
Rails.application.routes.draw do
  
  devise_for :persns
  get 'dashboards/index'
  

  root 'dashboards#index'

end

app/models/persn.rb
class Persn < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/index.html.erb
<div class="jumbotron" >
<h1>Workout Lounge!</h1>
<p>Show off your workout for friends</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 
</head>
<body>
<header role="banner">
<nav class ="navbar navbar-default navbar-fixed-top" role ="navigation">
<div class ="container-fluid">
<div class="navbar-header"
<button type="button"
class ="navbar-toggle"
data-toggle = "collapse"
data-target = "#bs-example-navbar-collapse-2">	
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<%= link_to "Athletes Den",root_path ,class: "navbar-brand" %>
</div>
<div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
<ul class ="nav navbar-nav">
<li class="active">
<%= link_to "Home",root_path %></li>
</ul>
<ul class ="nav navbar-nav navbar-right">
	<li><%=  link_to "Sign up",new_persn_registration_path,class: "navbar-brand" %></li>
	<li><%=  link_to "Sign in",new_persn_session_path ,class: "navbar-brand"%></li>
	

	<% if persn_signed_in? %>
	<div class="navbar-right">
	<p class="navbar-text">
	Signed in as <%= "#{current_persn.email}" %>
	</p>
	</div>
<% end %>
</ul>


</div>
</div>
</nav>
</header>
<div class="row">
<div class="col-md-12">
<% flash.each do |key,message| %>
<div class= "text-center alert
					alert-<%= key =='notice' ? 'success' : 'danger' %>">
<%= message %>
</div>

<% end %>
</div>

<%= yield %>
</div>
</body>
</html>